name: Update Age

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
jobs:
  update_readme:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.10.13

    - name: Update Age
      run: |
        git config --global user.name "tripleseven190504"
        git config --global user.email "tripleseven190504@gmail.com"
        git pull
        python update_age.py
    - name: Commit and push changes
      run: |
        git add README.md
        git commit -m "Updated README.md" || echo "No changes to commit"
        git push
